1\. **PCA on 3D dataset**

* Generate a dataset simulating 3 features, each with N entries (N being ${\cal O}(1000)$). Each feature is made by random numbers generated according the normal distribution $N(\mu,\sigma)$ with mean $\mu_i$ and standard deviation $\sigma_i$, with $i=1, 2, 3$. Generate the 3 variables $x_{i}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues using the eigendecomposition of the covariance matrix
* Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained
* Redefine the data according to the new basis from the PCA
* Plot the data, in both the original and the new basis. The figure should have 2 rows (the original and the new basis) and 3 columns (the $[x_0, x_1]$, $[x_0, x_2]$ and $[x_1, x_2]$ projections) of scatter plots.

In [16]:
import numpy as np

#-->1<-- creo i 3 dataset
x1 = np.random.normal(loc=0, scale=1, size=1000)
x2 = x1 + np.random.normal(loc=0, scale=3, size=1000)
x3 = 2*x1 + x2

#-->2<-- 
matr = np.asmatrix(np.array([x1,x2,x3]))
matr_cov = np.cov(matr)
eigen_vals_cov, eigen_vecs_cov = np.linalg.eig(matr_cov)

#-->3<--
U, S, V = np.linalg.svd(matr) 

# Rescale the SVD spectrum to get the eigenvalues
eigen_vals_svd = S**2/(1000-1)
# The matrix U already contains the eigenvectors
eigen_vecs_svd = U

print(f"Eigenvalues Covariance:\n{eigen_vals_cov}")
print(f"Eigenvectors Covariance:\n{eigen_vecs_cov}")

print(f"\nEigenvalues SVD:\n{eigen_vals_svd}")
print(f"Eigenvectors SVD:\n{eigen_vecs_svd}")

Eigenvalues Covariance:
[2.67120342e+01 2.02243062e-15 2.03084116e+00]
Eigenvectors Covariance:
[[-0.1238784  -0.81649658  0.56390378]
 [-0.56675986 -0.40824829 -0.71562322]
 [-0.81451667  0.40824829  0.41218434]]

Eigenvalues SVD:
[2.67123577e+01 2.03084408e+00 4.38203260e-32]
Eigenvectors SVD:
[[-0.1238777   0.56390394 -0.81649658]
 [-0.56676075 -0.71562252 -0.40824829]
 [-0.81451615  0.41218536  0.40824829]]


2\. **PCA on a nD dataset**

* Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normally distributed, with a standard deviation much smaller (e.g. a factor 20) than those used to generate the $x_1$ and $x_2$. Repeat the PCA procedure and compare the results with what you have obtained before.

3\. **Optional**: **PCA on the MAGIC dataset**

Perform a PCA on the magic04.data dataset.

In [ ]:
# get the dataset and its description on the proper data directory
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P data/
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P data/ 